package com.jersey.models;

import java.sql.Date;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(name = "employees")
public class Employee {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Size(min = 5)
    @Column(name = "name")
    private String name;

    @NotNull
    @Size(min = 5)
    @Column(name = "position")
    private String position;

    @NotNull
    @Size(min = 5)
    @Column(name = "department")
    private String department;

    @NotNull
    @Column(name = "hire_date")
    private Date hireDate;

    @NotNull
    @Column(name = "salary")
    private double salary;

    // Getters and setters are autogenerated by Lombok
}
